activation: relu
activation_after_add: true
activation_dense: relu6
aleatoric_uncertainty: Homoscedastic
architecture: VNet
architecture_batch_normalization: false
architecture_renormalization: false
augment_dificult: 2
augment_train: true
bn_dense_block: false
classification_task: Multi-task_clf_and_Lung_Seg
employ_meta_info: true
eval_batch_size: 2
eval_delay_secs: 1
eval_steps: 2
experiment: experiment-2019-10-18-12-47-51-849100
hierarchy: false
init_bias: Bias_for_minority_class
keep_prob: 0.9
learning_rate: 1e-3
loss_fn: UNCERTAINTY_LOSS_SM_FL_C
min_eval_frequency: 1
multiple_opts: false
normalize_input: true
num_channels: 16
num_gpus: 1
num_levels: 4
num_parallel_calls: 6
optimizer: ADAM
optimizer_params: 0.99, 0.999, 1e-4
output_dir: /results/
renorm_dense_block: false
reports_path: /data/reports/TrainingSet_metaData_extra.csv
shared_fn: vnet_decoder
train_batch_size: 2
train_buffer_size: 200
train_imgs_dir: /data/TrainingSet_ISO_NS/
train_masks_dir: /data/TrainingSet_MASKS_ISO_NS/
train_steps: 300000
val_imgs_dir: /data/ValidationSet_ISO_NS/
val_masks_dir: /data/ValidationSet_MASKS_ISO_NS/
